#Requires -Version 5.1
<#
.SYNOPSIS
    One-time dev setup: locates Valheim + BepInEx, stages the reference assemblies every mod in
    this repo builds against into lib/, and writes Valheim.props (both gitignored).
    Safe to re-run after a game update.
#>
[CmdletBinding()]
param(
    # Override auto-detection of the Valheim install.
    [string]$ValheimDir,
    # Gale profile that scripts/deploy.ps1 installs into.
    [string]$GaleProfile = 'Default'
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'lib.ps1')

function Find-Valheim {
    $roots = @()
    $steam = (Get-ItemProperty 'HKCU:\Software\Valve\Steam' -ErrorAction SilentlyContinue).SteamPath
    if ($steam) { $roots += $steam }
    $roots += 'C:\Program Files (x86)\Steam'

    $libs = @()
    foreach ($r in $roots) {
        $libs += $r
        $vdf = Join-Path $r 'steamapps\libraryfolders.vdf'
        if (Test-Path $vdf) {
            $libs += ([regex]::Matches((Get-Content $vdf -Raw), '"path"\s+"([^"]+)"') |
                ForEach-Object { $_.Groups[1].Value -replace '\\', '\' })
        }
    }
    foreach ($l in ($libs | Select-Object -Unique)) {
        $p = Join-Path $l 'steamapps\common\Valheim'
        if (Test-Path (Join-Path $p 'valheim_Data\Managed\assembly_valheim.dll')) { return (Resolve-Path $p).Path }
    }
    return $null
}

function Find-BepInExCore {
    # Newest BepInEx we can find: game dir first, then Gale / r2modman profiles.
    $candidates = @(Join-Path $ValheimDir 'BepInEx\core')
    foreach ($base in @("$env:APPDATA\com.kesomannen.gale\valheim\profiles",
                        "$env:APPDATA\r2modmanPlus-local\Valheim\profiles")) {
        if (Test-Path $base) {
            $candidates += (Get-ChildItem $base -Directory | ForEach-Object { Join-Path $_.FullName 'BepInEx\core' })
        }
    }
    $found = $candidates |
        Where-Object { Test-Path (Join-Path $_ 'BepInEx.dll') } |
        Sort-Object { [version](Get-Item (Join-Path $_ 'BepInEx.dll')).VersionInfo.FileVersion } -Descending
    return $found | Select-Object -First 1
}

# --- .NET SDK -----------------------------------------------------------------
if (-not (Get-Command dotnet -ErrorAction SilentlyContinue) -or -not (dotnet --list-sdks)) {
    Write-Host 'No .NET SDK found. Installing via winget...' -ForegroundColor Yellow
    winget install --id Microsoft.DotNet.SDK.8 --accept-source-agreements --accept-package-agreements
    Write-Host 'SDK installed - open a new shell and re-run this script.' -ForegroundColor Yellow
    exit 0
}

# --- game ---------------------------------------------------------------------
if (-not $ValheimDir) { $ValheimDir = Find-Valheim }
if (-not $ValheimDir -or -not (Test-Path $ValheimDir)) {
    throw 'Valheim not found. Re-run with -ValheimDir "<path to Valheim>".'
}
$managed = Join-Path $ValheimDir 'valheim_Data\Managed'
$unity = (Get-Item (Join-Path $ValheimDir 'valheim.exe')).VersionInfo.ProductVersion
Write-Host "Valheim : $ValheimDir (Unity $unity)"

$core = Find-BepInExCore
if (-not $core) { throw 'BepInEx not found. Install the BepInEx pack in your mod manager first.' }
Write-Host ("BepInEx : $core ({0})" -f (Get-Item (Join-Path $core 'BepInEx.dll')).VersionInfo.FileVersion)

# Each mod is deployed into <profile>\BepInEx\plugins\<author>-<mod>\.
$profileDir = "$env:APPDATA\com.kesomannen.gale\valheim\profiles\$GaleProfile"
Write-Host "Profile : $profileDir"
Write-Host ("Mods    : {0}" -f ((Get-Mods) -join ', '))

# --- stage lib/ ---------------------------------------------------------------
$lib = Join-Path $Root 'lib'
if (Test-Path $lib) { Remove-Item $lib -Recurse -Force }
New-Item -ItemType Directory $lib | Out-Null

Copy-Item (Join-Path $managed 'assembly_*.dll') $lib
Copy-Item (Join-Path $managed 'Assembly-CSharp.dll') $lib
Copy-Item (Join-Path $managed 'UnityEngine*.dll') $lib
# Splatform holds PlatformUserID, which Minimap.PinData and AddPin take.
Copy-Item (Join-Path $managed 'Splatform*.dll') $lib
foreach ($dll in 'BepInEx.dll', '0Harmony.dll', 'BepInEx.Harmony.dll') {
    $src = Join-Path $core $dll
    if (Test-Path $src) { Copy-Item $src $lib }
}
Write-Host ("lib/    : {0} assemblies" -f (Get-ChildItem $lib -Filter *.dll).Count)

# --- Valheim.props ------------------------------------------------------------
@"
<Project>
  <!-- Generated by scripts/setup.ps1 - do not commit. -->
  <PropertyGroup>
    <ValheimDir>$ValheimDir</ValheimDir>
    <ProfileDir>$profileDir</ProfileDir>
  </PropertyGroup>
</Project>
"@ | Set-Content (Join-Path $Root 'Valheim.props') -Encoding UTF8

Push-Location $Root
try { foreach ($mod in Get-Mods) { if (-not (Test-Pack $mod)) { dotnet restore (Join-Path (Get-ModDir $mod) "$mod.csproj") } } } finally { Pop-Location }

Write-Host ''
Write-Host 'Setup done. Next: scripts\deploy.ps1 (build + install), scripts\decompile.ps1 (game source).' -ForegroundColor Green
